# Generated by Django 3.2.15 on 2022-10-05 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machine', '0003_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('model_name', models.CharField(max_length=100)),
                ('profile_name', models.CharField(blank=True, max_length=50, null=True)),
                ('software_version', models.CharField(blank=True, max_length=10, null=True)),
                ('layer_count', models.PositiveSmallIntegerField()),
                ('layer_thickness', models.PositiveIntegerField()),
                ('finished_layers', models.PositiveIntegerField()),
                ('print_status', models.CharField(choices=[('successful', 'Successful'), ('unsuccessful', 'Unsuccessful'), ('cancelled', 'Cancelled'), ('faulty', 'Faulty')], default='faulty', max_length=12)),
                ('start_type', models.CharField(blank=True, choices=[('normal', 'NoHeating'), ('quickstart', 'Quickstart'), ('overtime', 'Overtime'), ('overtemp', 'Overtemp')], default='normal', max_length=10, null=True)),
                ('start_temp', models.FloatField(blank=True, null=True)),
                ('total_solid_area', models.FloatField()),
                ('exposure', models.FloatField()),
                ('print_start', models.DateTimeField()),
                ('print_real_start', models.DateTimeField(blank=True, null=True)),
                ('print_stop', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_logs', to='machine.machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Print Logs',
            },
        ),
    ]
