# Generated by Django 3.2.15 on 2022-10-05 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machine', '0004_printlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to=settings.AUTH_USER_MODEL),
        ),
    ]
