# Generated by Django 3.2.15 on 2022-10-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0005_alter_machine_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='profiles',
            field=models.ManyToManyField(related_name='machines', to='machine.Profile'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='unconfirmed_profiles',
            field=models.ManyToManyField(blank=True, to='machine.Profile'),
        ),
    ]
